# Generated by Django 3.2.6 on 2021-08-13 17:09

import ckeditor.fields
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=130, unique=True, verbose_name='Ссылка')),
                ('year_of_foundation', models.PositiveSmallIntegerField(default=2010, verbose_name='Год основания')),
                ('foundation_country', django_countries.fields.CountryField(max_length=2)),
                ('ceo', models.CharField(max_length=40, verbose_name='Генеральный директор')),
                ('employees_num', models.IntegerField(default=0, verbose_name='Количество сотрудников')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField()),
                ('release_date', models.DateField(auto_now_add=True, verbose_name='Дата выхода')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('title_image', models.ImageField(blank=True, default='default.jpg', upload_to='title_images', verbose_name='Главная картинка')),
                ('company', models.ManyToManyField(related_name='company', to='mainpage.Company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
