# Generated by Django 3.2.6 on 2021-08-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=130, null=True, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=130, null=True, unique=True, verbose_name='Ссылка'),
        ),
    ]
